apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: shell
    image: busybox
    command: ["sleep", "3600"]
    volumeMounts:
    - name: data
      mountPath: /data
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: backup-pvc
