apiVersion: v1
kind: PersistentVolume
metadata:
  name: backup-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""  # Added this line
  hostPath:
    path: /run/desktop/mnt/host/c/Users/Aayush/OneDrive/Documents/College/SEM6/CC/drive-backup-util/quickstart/backup
    type: DirectoryOrCreate

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: backup-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: backup-pv
  storageClassName: ""  # Added this line